FROM continuumio/miniconda3

COPY src/env/conda-env.yml /tmp/
RUN conda env create -f /tmp/conda-env.yml && conda clean -afy

COPY src /src
WORKDIR /src
ENV PATH /opt/conda/envs/gp-env/bin:$PATH

RUN chmod +x start-gp-server.sh
CMD ./start-gp-server.sh
