FROM hellej/green-path-server-base

COPY src /src
WORKDIR /src

ADD https://a3s.fi/swift/v1/AUTH_c1dfd63531fb4a63a3927b1f237b547f/gp-data/kumpula.graphml /src/graphs/
ADD https://a3s.fi/swift/v1/AUTH_c1dfd63531fb4a63a3927b1f237b547f/gp-data/hma.graphml /src/graphs/

RUN chmod +x start-aqi-updater.sh
CMD ./start-aqi-updater.sh
