name: gp-env

channels:
  - conda-forge
dependencies:
  - python=3.7
  - pylint
  - pytest
  - rasterio
  - rioxarray
  - xarray
  - boto3
  - apscheduler
  - geopandas
  - flask
  - flask-cors
  - pip
  - pip:
    - python_igraph-0.7.1.post6-cp37-cp37m-win_amd64.whl
