name: gp-env

channels:
  - conda-forge
dependencies:
  - python=3.8
  - pylint
  - pytest
  - apscheduler
  - geopandas
  - python-igraph
  - flask
  - flask-cors
  - flask-testing
  - gunicorn
  # aqi_updater
  - rasterio
  - rioxarray
  - xarray
  - boto3
  # graph_build
  - requests
  - owslib
  - sqlalchemy
  - psycopg2
  - geoalchemy2
