name: gp-env

channels:
  - conda-forge
dependencies:
  - python=3.8
  - pylint
  - pytest
  - rasterio
  - rioxarray
  - xarray
  - boto3
  - apscheduler
  - geopandas
  - python-igraph
  - flask
  - flask-cors
  - flask-testing
  - gunicorn
