name: Build GP base image
on:
  push:
    branches-ignore:
      - 'master'
    paths:
      - 'src/env/conda-env.yml'

jobs:
  docker-build-push-gp-base-image:
    name: Build GP base image
    runs-on: ubuntu-18.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Dockerfile.base
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/green-path-server-base:latest
          cache-from: type=registry,ref=hellej/green-path-server-base:latest
          cache-to: type=inline
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
